Repository gominima/minima, pull requests merged in 2022-02, with the labels that each got.

#28 feat(Response): Get status code by methods
  res_header.go
  response.go
Labels: 📈enhancement, ⚡good first issue

#36 feat: Hash table implementation
  README.md
  _examples/start.go
  minima.go
  mux.go
  mux_test.go
  request.go
  response.go
  router.go
Labels: 📈enhancement

#43 docs: update the CoC to the latest version
  CODE_OF_CONDUCT.md
Labels: 📑documentation
